# Generated by Django 5.0.2 on 2024-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
